#!/bin/sh

set -e

output=$1; shift

cabal new-configure --enable-optimization --enable-executable-stripping
cabal new-build

find dist-newstyle -type f -name xmonad-conf \
     -exec cp '{}' $output ';'
